# Generated by Django 5.1.15 on 2026-07-11 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude centre')),
                ('center_lng', models.FloatField(blank=True, null=True, verbose_name='Longitude centre')),
                ('zoom', models.FloatField(default=14.0, verbose_name='Zoom initial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='tenants.tenant', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'simulation',
                'verbose_name_plural': 'simulations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('antenna', 'Antenne'), ('cpe', 'CPE client'), ('relay', 'Relais'), ('tower', 'Tour/mât')], db_index=True, max_length=16)),
                ('label', models.CharField(blank=True, max_length=64, verbose_name='Libellé')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='simulation.simulation')),
            ],
            options={
                'verbose_name': 'élément de simulation',
                'verbose_name_plural': 'éléments de simulation',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('ptmp', 'Point-à-multipoint'), ('ptp', 'Point-à-point')], default='ptmp', max_length=8)),
                ('config', models.JSONField(default=dict, verbose_name='Paramètres')),
                ('result', models.JSONField(default=dict, verbose_name='Résultat calculé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_a', to='simulation.simulationelement')),
                ('element_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_b', to='simulation.simulationelement')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='simulation.simulation')),
            ],
            options={
                'verbose_name': 'lien de simulation',
                'verbose_name_plural': 'liens de simulation',
                'ordering': ['created_at'],
            },
        ),
    ]
