# Generated by Django 5.1.15 on 2026-03-28 21:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def forwards_accountant_to_revendeur(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="accountant").update(role="revendeur")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_accountant_to_revendeur, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='can_sell_tickets',
        ),
        migrations.AddField(
            model_name='user',
            name='default_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Taux appliqué aux ventes de tickets Wi-Fi Zone (ex. 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Commission par défaut (%)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technician', 'Technicien'), ('revendeur', 'Revendeur')], db_index=True, default='technician', max_length=20),
        ),
    ]
