# Generated by Django 5.1.15 on 2026-04-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_platform_operator'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Vide pour les super-utilisateurs plateforme ; obligatoire pour le personnel d’un FAI.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant', verbose_name='Organisation'),
        ),
    ]
