# Generated by Django 5.1.15 on 2026-05-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_tenant'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket_prefix',
            field=models.CharField(blank=True, db_index=True, help_text='Préfixe unique assigné à ce revendeur (ex. KONE, REV01). Lettres majuscules et chiffres uniquement, 2 à 10 caractères. Les codes générés auront la forme PREFIX-XXXXXXXX.', max_length=10, verbose_name='Préfixe tickets'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_prefix__gt', '')), fields=('ticket_prefix',), name='accounts_user_ticket_prefix_uniq'),
        ),
    ]
