# Generated by Django 6.0.3 on 2026-03-28 21:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income', 'Entrée (recette)'), ('expense', 'Dépense (maintenance / autre)')], db_index=True, max_length=16)),
                ('amount_xof', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (XOF)')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text="Ex. carburant, main-d'œuvre, consommables, vente ticket…", max_length=64, verbose_name='Catégorie')),
                ('entry_date', models.DateField(db_index=True, verbose_name='Date comptable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries_created', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='core.site', verbose_name='Site lié (optionnel)')),
            ],
            options={
                'verbose_name': 'écriture de caisse',
                'verbose_name_plural': 'journal de caisse',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('assigned', 'Assigné'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_tickets', to='core.site')),
            ],
            options={
                'verbose_name': "ticket d'intervention",
                'verbose_name_plural': "tickets d'intervention",
                'ordering': ['-opened_at'],
            },
        ),
    ]
