# Generated by Django 5.1.15 on 2026-03-28 21:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ptplink'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='faulty_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='core.ptplink', verbose_name='Liaison PtP défectueuse'),
        ),
        migrations.CreateModel(
            name='CaisseDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, unique=True, verbose_name='Date')),
                ('wifi_zone_gross_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Total encaissements bruts tickets Wi-Fi Zone.', max_digits=14, verbose_name='Brut tickets Zone (XOF)')),
                ('wifi_zone_commissions_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Commissions revendeurs (XOF)')),
                ('wifi_zone_net_isp_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Net FAI après commissions Zone (XOF)')),
                ('wifi_simple_collected_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Paiements abonnements mensuels du jour.', max_digits=14, verbose_name='Encaissements Wi-Fi Simple (XOF)')),
                ('other_income_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Autres recettes (XOF)')),
                ('expenses_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Dépenses du jour (XOF)')),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisse_reports_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rapport de caisse quotidien',
                'verbose_name_plural': 'rapports de caisse quotidiens',
                'ordering': ['-report_date'],
            },
        ),
    ]
