# Generated by Django 5.1.15 on 2026-05-21 02:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_multi_tenant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevendeurDailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='Date')),
                ('prefix', models.CharField(blank=True, max_length=10, verbose_name='Préfixe utilisé')),
                ('tickets_sold_count', models.PositiveIntegerField(default=0, verbose_name='Tickets vendus')),
                ('tickets_used_count', models.PositiveIntegerField(default=0, verbose_name='Tickets utilisés')),
                ('gross_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Montant brut (XOF)')),
                ('commission_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Commissions (XOF)')),
                ('net_isp_xof', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14, verbose_name='Net FAI (XOF)')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Généré le')),
                ('detail_json', models.JSONField(default=list, verbose_name='Détail tickets')),
                ('revendeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Revendeur')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revendeur_daily_reports', to='tenants.tenant', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'rapport journalier revendeur',
                'verbose_name_plural': 'rapports journaliers revendeurs',
                'ordering': ['-report_date', 'revendeur'],
                'constraints': [models.UniqueConstraint(fields=('revendeur', 'report_date'), name='finance_revendeurreport_revendeur_date_uniq')],
            },
        ),
    ]
