# Generated by Django 6.0.3 on 2026-03-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du site')),
                ('site_id', models.CharField(db_index=True, help_text='Identifiant aligné sur Zabbix / routeurs / procédures terrain.', max_length=64, unique=True, verbose_name='Identifiant site (réf. expl.)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_operational', models.BooleanField(default=True, help_text='Mis à jour manuellement ou par le monitoring.', verbose_name='Site opérationnel (carte verte)')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('vendor', models.CharField(choices=[('ubiquiti', 'Ubiquiti'), ('mikrotik', 'MikroTik'), ('other', 'Autre')], default='other', max_length=20)),
                ('management_host', models.CharField(max_length=255, verbose_name='IP / hostname')),
                ('api_port', models.PositiveIntegerField(default=443)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('password_hint', models.CharField(blank=True, help_text='Ne pas stocker le mot de passe en clair en prod.', max_length=128, verbose_name='Réf. secret (Vault)')),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'équipement réseau',
                'verbose_name_plural': 'équipements réseau',
            },
        ),
    ]
