# Generated by Django 5.1.15 on 2026-03-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtPLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('endpoint_a_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lat. antenne A')),
                ('endpoint_a_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lng. antenne A')),
                ('endpoint_b_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lat. antenne B')),
                ('endpoint_b_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Lng. antenne B')),
                ('zabbix_host_a', models.CharField(blank=True, help_text="Nom d'hôte tel que dans Zabbix (items SNMP RSSI / bruit / débit).", max_length=128, verbose_name='Host Zabbix (extrémité A)')),
                ('zabbix_host_b', models.CharField(blank=True, max_length=128, verbose_name='Host Zabbix (extrémité B)')),
                ('snmp_management_ip', models.GenericIPAddressField(blank=True, help_text='Optionnel : interrogation directe airMAX en complément de Zabbix.', null=True, protocol='IPv4', verbose_name='IP SNMP (sonde directe pysnmp)')),
                ('snmp_community_secret_ref', models.CharField(blank=True, max_length=128, verbose_name='Réf. communauté SNMP (vault)')),
                ('cached_health', models.CharField(choices=[('up', 'OK (vert)'), ('degraded', 'Dégradé (orange)'), ('down', 'Hors service (rouge)'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=16)),
                ('cached_health_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptp_links_as_a', to='core.site', verbose_name='Site extrémité A')),
                ('site_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptp_links_as_b', to='core.site', verbose_name='Site extrémité B')),
            ],
            options={
                'verbose_name': 'liaison PtP',
                'verbose_name_plural': 'liaisons PtP',
                'ordering': ['name'],
            },
        ),
    ]
