# Generated by Django 5.1.15 on 2026-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_site_wifi_zone_hotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='password_hint',
            field=models.CharField(blank=True, help_text='Ne pas stocker le mot de passe en clair en prod. Ex. env:MIKROTIK_PASS_SITE12', max_length=128, verbose_name='Réf. secret (Vault)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='wifi_zone_hotspot_profile',
            field=models.CharField(blank=True, help_text='Si renseigné : ce profil est utilisé pour toutes les durées de tickets sur ce site. Si vide : profils par durée via les variables MIKROTIK_HOTSPOT_PROFILE_3H, _1D, _1W, _30J (défauts Profil-2H, Profil-24H, 7j, Profil-30Jours).', max_length=64, verbose_name='Profil Hotspot RouterOS'),
        ),
    ]
