# Generated by Django 5.1.15 on 2026-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_hotspot_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_1d',
            field=models.CharField(blank=True, help_text='Profil pour les tickets 1 jour. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 24 h (1 jour)'),
        ),
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_1w',
            field=models.CharField(blank=True, help_text='Profil pour les tickets 1 semaine. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 7 jours'),
        ),
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_30j',
            field=models.CharField(blank=True, help_text='Profil pour les tickets 30 jours. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 30 jours'),
        ),
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_3h',
            field=models.CharField(blank=True, help_text='Nom exact du profil /ip hotspot user profile pour les tickets 3 h. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 3 h'),
        ),
        migrations.AlterField(
            model_name='site',
            name='wifi_zone_hotspot_profile',
            field=models.CharField(blank=True, help_text='Optionnel : un seul profil RouterOS pour tous les tickets de ce site. Si vide, utilisation des profils par durée ci‑dessous, puis des valeurs globales (.env / settings).', max_length=64, verbose_name='Profil Hotspot (toutes durées)'),
        ),
    ]
