# Generated by Django 5.1.15 on 2026-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_networkdevice_encrypted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='password_hint',
            field=models.CharField(blank=True, help_text='Référence à une variable d’environnement : ex. env:MIKROTIK_PASS_SITE12. Laisser vide si le mot de passe est défini via le champ ‘Définir le mot de passe’ ci-dessous.', max_length=128, verbose_name='Réf. secret (env var)'),
        ),
    ]
