# Generated by Django 6.0.6 on 2026-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_site_wifi_zone_profiles_1w_illimite'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_2h',
            field=models.CharField(blank=True, help_text='Profil pour les tickets 2 heures. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 2 h'),
        ),
        migrations.AddField(
            model_name='site',
            name='wifi_zone_profile_4h',
            field=models.CharField(blank=True, help_text='Profil pour les tickets 4 heures. Vide = défaut global.', max_length=64, verbose_name='Profil hotspot — 4 h'),
        ),
    ]
