# Generated by Django 6.0.3 on 2026-03-28 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAbonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Téléphone')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='core.site', verbose_name='Site de raccordement')),
            ],
            options={
                'verbose_name': 'client abonné',
                'verbose_name_plural': 'clients abonnés',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('duration', models.CharField(choices=[('1h', '1 heure'), ('24h', '24 heures'), ('30j', '30 jours')], db_index=True, max_length=8)),
                ('price_xof', models.DecimalField(decimal_places=0, help_text='Franc CFA BCEAO.', max_digits=12, verbose_name='Prix (XOF)')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('used', 'Utilisé'), ('expired', 'Expiré')], db_index=True, default='available', max_length=16)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wifi_tickets', to='core.site', verbose_name='Site')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_tickets_sold', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur (technicien / revendeur)')),
            ],
            options={
                'verbose_name': 'ticket Wi-Fi',
                'verbose_name_plural': 'tickets Wi-Fi',
                'ordering': ['-created_at'],
            },
        ),
    ]
