# Generated by Django 5.1.15 on 2026-03-28 21:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ptplink"),
        ("wifi_zone", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ticket Wi-Fi Zone",
                "verbose_name_plural": "tickets Wi-Fi Zone",
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="commission_amount_xof",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Commission (XOF)",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="commission_rate_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Taux commission (%)",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Utilisé ?"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="net_to_isp_xof",
            field=models.DecimalField(
                decimal_places=0,
                default=Decimal("0"),
                help_text="Montant dû à l'opérateur après commission.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Net FAI (XOF)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price_xof",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Franc CFA BCEAO — montant encaissé côté revendeur ou PDV.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Prix (XOF)",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="sold_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wifi_tickets_sold",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revendeur / vendeur",
            ),
        ),
        migrations.RenameModel(
            old_name="ClientAbonne",
            new_name="WiFiSimpleSubscriber",
        ),
        migrations.AlterModelTable(
            name="wifisimplesubscriber",
            table="wifi_zone_clientabonne",
        ),
        migrations.AlterModelOptions(
            name="wifisimplesubscriber",
            options={
                "ordering": ["-expires_at"],
                "verbose_name": "abonné Wi-Fi Simple",
                "verbose_name_plural": "abonnés Wi-Fi Simple",
            },
        ),
        migrations.AddField(
            model_name="wifisimplesubscriber",
            name="mac_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Format AA:BB:CC:DD:EE:FF — utilisé pour blocage / déblocage.",
                max_length=17,
                verbose_name="Adresse MAC (CPE / client)",
            ),
        ),
        migrations.AddField(
            model_name="wifisimplesubscriber",
            name="is_payment_current",
            field=models.BooleanField(
                db_index=True,
                default=True,
                verbose_name="Abonnement payé à jour",
            ),
        ),
        migrations.AddField(
            model_name="wifisimplesubscriber",
            name="mac_blocked_on_network",
            field=models.BooleanField(
                default=False,
                help_text="Synchronisé après commande SSH réussie.",
                verbose_name="MAC bloquée sur le réseau",
            ),
        ),
        migrations.AddField(
            model_name="wifisimplesubscriber",
            name="last_billing_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wifisimplesubscriber",
            name="cpe_device",
            field=models.ForeignKey(
                blank=True,
                help_text="Cible des commandes SSH / blocage MAC.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wifi_simple_subscribers",
                to="core.networkdevice",
                verbose_name="Équipement (routeur / AP)",
            ),
        ),
        migrations.AlterField(
            model_name="wifisimplesubscriber",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wifi_simple_subscribers",
                to="core.site",
                verbose_name="Site de raccordement",
            ),
        ),
        migrations.CreateModel(
            name="WifiTicketBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=128, verbose_name="Libellé")),
                (
                    "duration",
                    models.CharField(
                        choices=[("1h", "1 heure"), ("24h", "24 heures"), ("30j", "30 jours")],
                        db_index=True,
                        max_length=8,
                    ),
                ),
                (
                    "unit_price_xof",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire (XOF)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Nombre de tickets",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wifi_ticket_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wifi_ticket_batches",
                        to="core.site",
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "lot de tickets Wi-Fi",
                "verbose_name_plural": "lots de tickets Wi-Fi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="wifi_zone.wifiticketbatch",
                verbose_name="Lot d'origine",
            ),
        ),
    ]
