# Generated by Django 5.1.15 on 2026-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_zone', '0004_align_ticket_duration_mikrotik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.CharField(choices=[('3h', '3 heures'), ('1d', '24 heures (1 jour)'), ('1w', '7 jours'), ('30j', '30 jours')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hotspot_synced_at',
            field=models.DateTimeField(blank=True, help_text='Routeur MikroTik : utilisateur présent ; vidé après retrait / erreur.', null=True, verbose_name='Dernier provisionnement Hotspot'),
        ),
        migrations.AlterField(
            model_name='wifiticketbatch',
            name='duration',
            field=models.CharField(choices=[('3h', '3 heures'), ('1d', '24 heures (1 jour)'), ('1w', '7 jours'), ('30j', '30 jours')], db_index=True, max_length=8),
        ),
    ]
