# Generated by Django 6.0.6 on 2026-07-11 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_networkdevice_password_hint'),
        ('tenants', '0001_initial'),
        ('wifi_zone', '0006_ticket_hotspot_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wifisimplesubscriber',
            options={'ordering': ['-expires_at'], 'verbose_name': 'abonné domicile', 'verbose_name_plural': 'abonnés domicile'},
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='ip_static',
            field=models.GenericIPAddressField(blank=True, help_text='IP client pour Simple Queue et ARP statique.', null=True, verbose_name='IP statique'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='quartier',
            field=models.CharField(blank=True, max_length=64, verbose_name='Quartier'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('expire', 'Expiré')], db_index=True, default='nouveau', max_length=16, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='+226XXXXXXXXX — laissez vide pour utiliser le numéro principal.', max_length=32, verbose_name='Numéro WhatsApp'),
        ),
        migrations.AlterField(
            model_name='wifisimplesubscriber',
            name='cpe_device',
            field=models.ForeignKey(blank=True, help_text='Équipement cible pour les commandes RouterOS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wifi_simple_subscribers', to='core.networkdevice', verbose_name='Routeur MikroTik'),
        ),
        migrations.AlterField(
            model_name='wifisimplesubscriber',
            name='mac_blocked_on_network',
            field=models.BooleanField(default=False, help_text='Synchronisé après commande RouterOS réussie.', verbose_name='MAC bloquée sur le réseau'),
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom du plan')),
                ('speed_mbps', models.PositiveIntegerField(default=2, verbose_name='Débit (Mbps)')),
                ('price_xof', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix mensuel (XOF)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_abonnement', to='tenants.tenant', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "plan d'abonnement",
                'verbose_name_plural': "plans d'abonnement",
                'ordering': ['price_xof'],
            },
        ),
        migrations.AddField(
            model_name='wifisimplesubscriber',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='wifi_zone.planabonnement', verbose_name='Plan souscrit'),
        ),
        migrations.CreateModel(
            name='TicketPlainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=32, verbose_name='Référence')),
                ('phone_from', models.CharField(blank=True, max_length=32, verbose_name='Téléphone expéditeur')),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('appel', 'Appel téléphonique'), ('manuel', 'Saisie manuelle')], db_index=True, default='manuel', max_length=16, verbose_name='Source')),
                ('message_original', models.TextField(verbose_name='Message original')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='Catégorie')),
                ('priority', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], db_index=True, default='moyenne', max_length=16, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], db_index=True, default='nouveau', max_length=16, verbose_name='Statut')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_plainte_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Technicien assigné')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_plainte', to='wifi_zone.wifisimplesubscriber', verbose_name='Abonné')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_plainte', to='tenants.tenant', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'ticket de plainte',
                'verbose_name_plural': 'tickets de plainte',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reference'), name='wifi_ticketplainte_tenant_reference_uniq')],
            },
        ),
    ]
