# Generated by Django 6.0.6 on 2026-08-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_zone', '0011_add_duration_1w_illimite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP attribuée au client lors de la connexion hotspot.', null=True, verbose_name='IP du client'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_used_at',
            field=models.DateTimeField(blank=True, help_text='Date/heure de la première connexion détectée via MikroTik.', null=True, verbose_name='Première utilisation'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Adresse MAC de l’appareil qui a activé le ticket (remontée depuis MikroTik).', max_length=17, null=True, verbose_name='MAC du client'),
        ),
    ]
