# Generated by Django 6.0.6 on 2026-08-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_zone', '0012_ticket_client_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.CharField(choices=[('2h', '2 heures'), ('3h', '3 heures'), ('4h', '4 heures'), ('1d', '24 heures (1 jour)'), ('5j', '5 jours'), ('1w', '7 jours'), ('30j', '30 jours'), ('illimite', 'Illimité')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='wifiticketbatch',
            name='duration',
            field=models.CharField(choices=[('2h', '2 heures'), ('3h', '3 heures'), ('4h', '4 heures'), ('1d', '24 heures (1 jour)'), ('5j', '5 jours'), ('1w', '7 jours'), ('30j', '30 jours'), ('illimite', 'Illimité')], db_index=True, max_length=8),
        ),
    ]
