# Generated by Django 6.0.6 on 2026-07-11 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_networkdevice_password_hint'),
        ('monitoring', '0003_routerauditlog_hotspot_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_principale', models.IntegerField(default=5180, verbose_name='Fréquence principale (MHz)')),
                ('freq_secours_1', models.IntegerField(blank=True, null=True, verbose_name='Fréquence secours 1 (MHz)')),
                ('freq_secours_2', models.IntegerField(blank=True, null=True, verbose_name='Fréquence secours 2 (MHz)')),
                ('freq_secours_3', models.IntegerField(blank=True, null=True, verbose_name='Fréquence secours 3 (MHz)')),
                ('seuil_snr_min', models.IntegerField(default=15, verbose_name='Seuil SNR minimum (dB)')),
                ('seuil_signal_min', models.IntegerField(default=-75, verbose_name='Seuil signal minimum (dBm)')),
                ('seuil_capacite_min', models.IntegerField(default=40, verbose_name='Seuil capacité minimum (%)')),
                ('auto_switch', models.BooleanField(default=True, verbose_name='Basculement automatique')),
                ('derniere_modif', models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification')),
                ('historique_json', models.JSONField(blank=True, default=list, verbose_name='Historique JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frequence_config', to='core.networkdevice', verbose_name='Antenne')),
            ],
            options={
                'verbose_name': 'configuration fréquence',
                'verbose_name_plural': 'configurations fréquences',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueFrequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq_avant', models.IntegerField(verbose_name='Fréquence avant (MHz)')),
                ('freq_apres', models.IntegerField(verbose_name='Fréquence après (MHz)')),
                ('raison', models.CharField(choices=[('snr_faible', 'SNR insuffisant'), ('interference', 'Interférence détectée'), ('manuel', 'Action manuelle'), ('secours', 'Basculement secours')], default='snr_faible', max_length=20)),
                ('snr_avant', models.FloatField(blank=True, null=True, verbose_name='SNR avant (dB)')),
                ('signal_avant', models.FloatField(blank=True, null=True, verbose_name='Signal avant (dBm)')),
                ('declencheur', models.CharField(choices=[('auto', 'Automatique'), ('manuel', 'Manuel'), ('urgence', 'Urgence')], default='auto', max_length=10)),
                ('resultat', models.CharField(choices=[('ameliore', 'Amélioré'), ('degrade', 'Dégradé'), ('neutre', 'Neutre')], default='neutre', max_length=10)),
                ('dry_run', models.BooleanField(default=False, verbose_name='Mode test')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_frequences', to='core.networkdevice', verbose_name='Antenne')),
            ],
            options={
                'verbose_name': 'historique fréquence',
                'verbose_name_plural': 'historiques fréquences',
                'ordering': ['-created_at'],
            },
        ),
    ]
