# Generated by Django 6.0.6 on 2026-07-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Destinataire')),
                ('message', models.TextField(verbose_name='Message')),
                ('success', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('error_message', models.CharField(blank=True, max_length=512, verbose_name='Erreur')),
                ('dry_run', models.BooleanField(default=True, verbose_name='Mode test')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'log WhatsApp',
                'verbose_name_plural': 'logs WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
